# Generated by Django 4.2.7 on 2024-01-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trivia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese', models.CharField(max_length=255)),
                ('english', models.CharField(max_length=255)),
                ('chinese1', models.CharField(max_length=255)),
                ('chinese2', models.CharField(max_length=255)),
                ('korean', models.CharField(max_length=255)),
                ('mongolian', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=15)),
                ('url1', models.CharField(max_length=255)),
                ('url2', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=1023, null=True)),
            ],
            options={
                'db_table': 'trivias',
            },
        ),
    ]
