# Generated by Django 4.2.7 on 2024-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sadosma', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trivia',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='trivia',
            name='address2',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
